name: Handle Staging Pull Requests

on:
  pull_request:
    branches:
      - staging
    types:
      - closed

jobs:
  handle-staging-and-auto-merge:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Fetch and Sync Staging
        run: |
          git fetch origin
          git checkout staging
          git pull origin staging

      - name: Merge Changes into Staging
        run: |
          git fetch origin ${GITHUB_HEAD_REF}
          git merge --no-ff FETCH_HEAD
          git push origin staging

      - name: Create Pull Request from Staging to Main
        uses: peter-evans/create-pull-request@v6
        with:
          branch: staging
          base: main
          title: "[AUTO-PR] Staging to Main"
          body: |
            This is an automated pull request to merge changes from **staging** to **main**.
          labels: |
            auto-pr
          commit-message: "[AUTO-PR] Staging to Main"

      - name: Auto-merge Pull Request
        uses: pascalgn/automerge-action@v0.14.3
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          merge-method: squash
