name: Handle Staging Pull Requests

on:
  pull_request:
    branches:
      - staging
    types:
      - closed

jobs:
  update-staging-and-create-auto-pr:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0 # Fetch toàn bộ lịch sử commit

      - name: Fetch and Checkout staging
        run: |
          git fetch origin staging
          git checkout staging

      - name: Merge Changes into Staging
        run: |
          git pull origin ${GITHUB_HEAD_REF} # Merge nhánh source của PR
          git push origin staging # Cập nhật staging

      - name: Create Pull Request from Staging to Main
        uses: peter-evans/create-pull-request@v6
        with:
          branch: "staging"
          base: "main"
          title: "[AUTO-PR] Staging to Main"
          body: |
            This is an automated pull request to merge changes from **staging** to **main**.

            Please review and approve the changes.
          labels: |
            auto-pr
            ci/cd
          commit-message: |
            [AUTO-PR] Staging to Main
          force: false # Đảm bảo không force push
